# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    branches: [ "feat/init" ] # master 分支提交时触发
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go #配置GO 环境
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build # 编译项目
        run: CGO_ENABLED=0 GOOS=linux go build -o main .

      - name: 发布到阿里云
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_PRIVATE_KEY }}
          #Scp参数
          ARGS: "-rltgoDzvO --delete"
          #源目录
          SOURCE: "./"
          #服务器Ip:换成你的服务器iP
          REMOTE_HOST:  ${{ secrets.ALIYUN_SERVER_HOST }}
          #用户
          REMOTE_USER: "root"
          #目标地址
          TARGET: "/root/app"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.ALIYUN_SERVER_HOST }}
          username: "root"
          #私钥
          password: ${{ secrets.ALIYUN_SERVER_PWD }}
          #docker run -d -p 80:80 -v $PWD/log:/app/log alpine:3.13
          script: |
            cd /root/app
            exit
